# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bHaNXixqfn1V3O7KtFhUZe-jWTW9Bo_k
"""

sample_text = 'Первый образец «нового стиля» граффити сохранился в древнегреческом городе Эфесе (на территории современной Турции). Местные гиды называют его рекламным сообщением проституции. Расположенное рядом с украшенной мозаикой и камнями дорогой граффити изображало отпечаток руки, отдалённо напоминающий сердце, отпечаток ноги и число. Это означало, что где-то поблизости находился публичный дом, отпечаток руки символизировал оплату[4].' 
print('DLINASTROKI', len(sample_text)) 
corrected_text = ''

for i in range(len(sample_text)): 
    symbol = sample_text[i]
    if symbol.isalpha() or symbol == ' ':
        corrected_text += symbol.upper()
import random

# print(list(corrected_text))
# exit()

words = corrected_text.split(sep=' ') + ['zalupa'] *99
words.append('zalupa')
# random.shuffle(words)

print(words)
a = [1,2,3] * 100
print(a, len(a))

b = 'asdasd' * 100
print(b)

print(type(words))
exit() 
print(words) 
for i in range(len(words)): 
    word = words[i] 
    print(i, word)
    #if word == 'на':  #cтрогое равенство 
    if 'на' in word:   #наличие подстроки в строке
        print('+' * 20)
   
print('CHEESLOSLOV', len(words))